name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Pull from Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE }}
        run: git pull https://umeshkhatiwada13:$HF_TOKEN@huggingface.co/spaces/umeshkhatiwada13/football_chatbot main
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE }}
        run: git push https://umeshkhatiwada13:$HF_TOKEN@huggingface.co/spaces/umeshkhatiwada13/football_chatbot main
