name: Sync to Hugging Face hub
on:
  push:
    branches: [main]

  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Pull from Hugging Face with rebase
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE }}
        run: |
          git config pull.rebase true
          git pull --rebase https://umeshkhatiwada13:${{ secrets.HUGGINGFACE }}@huggingface.co/spaces/umeshkhatiwada13/football_chatbot main || git rebase --abort

      - name: Resolve conflicts and push
        run: |
          git status
          git add .  # Add resolved files
          git push https://umeshkhatiwada13:${{ secrets.HUGGINGFACE }}@huggingface.co/spaces/umeshkhatiwada13/football_chatbot main
