name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Add commands to run your tests if any

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        run: |
          pip install huggingface_hub
          huggingface-cli login --token ${{ secrets.HUGGINGFACE }}
          huggingface-cli repo create football_bot --type=space --token ${{ secrets.HUGGINGFACE }}
          git lfs install
          git lfs track "*.bin"
          git add .gitattributes
          git add .
          git commit -m "Deploy to Hugging Face Space"
          git push https://huggingface.co/spaces/umeshkhatiwada13/football_chatbot main
